import type { ForgeConfig } from '@electron-forge/shared-types';
import { MakerZIP } from '@electron-forge/maker-zip';
import { MakerDeb } from '@electron-forge/maker-deb';
import { MakerRpm } from '@electron-forge/maker-rpm';
import { VitePlugin } from '@electron-forge/plugin-vite';
import { FusesPlugin } from '@electron-forge/plugin-fuses';
import { FuseV1Options, FuseVersion } from '@electron/fuses';

const config: ForgeConfig = {
  packagerConfig: {
    // Unpack the plugin-UI preload so <webview preload> can load it from a real
    // file path (webview preloads don't load reliably from inside app.asar).
    // Bare filename → asar matches it via minimatch `matchBase` (a pattern with
    // slashes would disable matchBase and miss the backslashed asar path).
    asar: { unpack: 'plugin-preload.js' },
    // App/exe icon; forge appends the platform extension (.ico on Windows).
    icon: './assets/icon',
    // Ship assets/ (window icon) and bundled-plugins/ (pre-packed, obfuscated
    // .orcpkg seeds). On first run they're installed into <userData>/plugins/
    // and loaded from there — see src/main/plugins/install.ts seedBundledPlugins.
    // Generated by `npm run pack:bundled` (also wired as the `prepackage` hook).
    extraResource: ['./assets', './bundled-plugins'],
  },
  rebuildConfig: {},
  // The Windows installer is built by electron-builder (NSIS wizard) via the
  // `build:win` script — see electron-builder.yml. These makers cover the other
  // platforms / a plain zip for `electron-forge make`.
  makers: [
    new MakerZIP({}, ['darwin']),
    new MakerRpm({}),
    new MakerDeb({}),
  ],
  plugins: [
    new VitePlugin({
      // `build` can specify multiple entry builds, which can be Main process, Preload scripts, Worker process, etc.
      // If you are familiar with Vite configuration, it will look really familiar.
      build: [
        {
          // `entry` is just an alias for `build.lib.entry` in the corresponding file of `config`.
          entry: 'src/main/index.ts',
          config: 'vite.main.config.ts',
          target: 'main',
        },
        {
          entry: 'src/preload/index.ts',
          config: 'vite.preload.config.ts',
          target: 'preload',
        },
        {
          // Sandboxed preload loaded by each view-plugin <webview>.
          entry: 'src/preload/plugin.ts',
          config: 'vite.plugin-preload.config.ts',
          target: 'preload',
        },
      ],
      renderer: [
        {
          name: 'main_window',
          config: 'vite.renderer.config.ts',
        },
      ],
    }),
    // Fuses are used to enable/disable various Electron functionality
    // at package time, before code signing the application
    new FusesPlugin({
      version: FuseVersion.V1,
      [FuseV1Options.RunAsNode]: false,
      [FuseV1Options.EnableCookieEncryption]: true,
      [FuseV1Options.EnableNodeOptionsEnvironmentVariable]: false,
      [FuseV1Options.EnableNodeCliInspectArguments]: false,
      [FuseV1Options.EnableEmbeddedAsarIntegrityValidation]: true,
      [FuseV1Options.OnlyLoadAppFromAsar]: true,
    }),
  ],
};

export default config;
